<x-app-layout>

    <x-slot name="header">

        <div>
            <h2 class="text-2xl font-bold text-gray-900">
                Scan QR Code
            </h2>

            <p class="mt-1 text-sm text-gray-500">
                Scan a swine QR code to view its identification and traceability records.
            </p>
        </div>

    </x-slot>


    <div class="py-8">

        <div class="mx-auto max-w-2xl px-4 sm:px-6 lg:px-8">

            <div class="overflow-hidden rounded-xl bg-white shadow-sm ring-1 ring-gray-200">

                {{-- Header --}}
                <div class="border-b border-gray-200 px-6 py-5">

                    <h3 class="text-lg font-semibold text-gray-900">
                        QR Code Scanner
                    </h3>

                    <p class="mt-1 text-sm text-gray-500">
                        Position the swine QR code inside the scanner.
                    </p>

                </div>


                {{-- Scanner Area --}}
                <div class="px-6 py-8">

                    <div id="qr-reader"
                        class="mx-auto w-full max-w-md overflow-hidden rounded-xl border border-gray-200">
                    </div>

                </div>


                {{-- Status --}}
                <div class="border-t border-gray-200 bg-gray-50 px-6 py-4">

                    <p id="scanner-status" class="text-center text-sm text-gray-500">
                        Waiting for camera...
                    </p>

                </div>

            </div>

        </div>

    </div>


    {{-- QR Scanner Library --}}
    <script src="https://unpkg.com/html5-qrcode" type="text/javascript"></script>


    <script>
        document.addEventListener('DOMContentLoaded', function () {
            const status = document.getElementById('scanner-status');
            const scanner = new Html5Qrcode('qr-reader');

            function isValidSwineLocateQr(decodedText) {
                try {
                    const url = new URL(decodedText);

                    // Must use the same domain as the current SwineLocate application
                    if (url.origin !== window.location.origin) {
                        return false;
                    }

                    // Must follow the SwineLocate QR scan route
                    const expectedPrefix = '/qr/scan/';

                    if (!url.pathname.startsWith(expectedPrefix)) {
                        return false;
                    }

                    // Get the QR token after /qr/scan/
                    const qrToken = url.pathname.substring(expectedPrefix.length);

                    // QR token must not be empty
                    if (!qrToken) {
                        return false;
                    }

                    // Prevent extra path segments
                    if (qrToken.includes('/')) {
                        return false;
                    }

                    return true;

                } catch (error) {
                    return false;
                }
            }

            function onScanSuccess(decodedText) {

                // Reject QR codes that are not generated by SwineLocate
                if (!isValidSwineLocateQr(decodedText)) {
                    status.textContent =
                        'Invalid QR code. Please scan a SwineLocate swine QR code.';

                    status.classList.remove('text-green-600');
                    status.classList.add('text-red-600');

                    return;
                }

                status.textContent =
                    'SwineLocate QR code detected. Opening traceability record...';

                status.classList.remove('text-red-600');
                status.classList.add('text-green-600');

                scanner.stop()
                    .then(function () {
                        window.location.href = decodedText;
                    })
                    .catch(function (error) {
                        console.error(error);
                        window.location.href = decodedText;
                    });
            }

            function onScanFailure(errorMessage) {
                // Ignore normal scanning failures
            }

            scanner.start(
                { facingMode: 'environment' },
                {
                    fps: 10,
                    qrbox: {
                        width: 250,
                        height: 250
                    }
                },
                onScanSuccess,
                onScanFailure
            )
                .then(function () {
                    status.textContent =
                        'Camera ready. Scan a SwineLocate swine QR code.';
                })
                .catch(function (error) {
                    console.error(error);

                    status.textContent =
                        'Unable to access the camera. Please allow camera permission.';

                    status.classList.remove('text-green-600');
                    status.classList.add('text-red-600');
                });
        });
    </script>

</x-app-layout>